package com.malletcrafts.sitephotos.pano

import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel

/**
 * The mark the app writes into every caption strip, so a photograph can name
 * itself after somebody else has been drawing on it.
 *
 * WHY THIS EXISTS. The filename is not an identity that survives the round
 * trip: ImageMeter renames its exports to image_from_19._Aug_2026.jpg, which
 * is how 88 returned files ended up in a review inbox saying "no capture id
 * in the filename". The caption strip DOES survive — ImageMeter draws on top
 * of the picture, never under it — but a strip of human words needs a human,
 * or OCR, to read. So the same strip now also carries a QR the app can read
 * back in a millisecond and be certain about.
 *
 * Amit, 2026-08-21: "As image is being generated by site foto apk, write
 * anything (any system code) as footer on image itself ... site foto app
 * written footer is the key to identify the foto and replace it with
 * annotated image from gallery."
 *
 * A QR rather than a row of coded pixels, which was the tempting
 * dependency-free option: ImageMeter may re-encode, resize or recompress
 * whatever it exports, and a QR is the one thing engineered to be read back
 * after exactly that. The pixel scheme would have needed its own locator,
 * its own scale detection and its own error correction — that is a QR, badly.
 *
 * Lives in :pano because it is pure JVM. The encode side, the payload
 * grammar and the parser are therefore tested in CI without a device, which
 * is the half of this that has bitten twice already.
 */
object Stamp {

    /** Marks the payload as OURS. A gallery is full of other people's QRs —
     *  a Wi-Fi card, a UPI handle, a parcel label — and decoding one of those
     *  into a capture id would attach a stranger's photo to a client's wall. */
    const val MAGIC = "MCFT1"

    private const val SEP = "|"

    /** MCFT1|MCAP-4b2014dcba5e|front — short on purpose. Every character is
     *  another QR module, and modules are what has to survive a re-encode. */
    fun payload(captureId: String, face: String): String =
        listOf(MAGIC, captureId, face).joinToString(SEP)

    data class Mark(val captureId: String, val face: String)

    /**
     * Read a payload back, or null.
     *
     * Strict about the magic and about the id's shape, permissive about
     * nothing else: a half-read QR that yields a plausible-looking id is the
     * one failure mode that silently files a photograph against the wrong
     * room, and it is worse than reading nothing at all.
     */
    fun parse(text: String?): Mark? {
        val parts = (text ?: "").split(SEP)
        if (parts.size != 3 || parts[0] != MAGIC) return null
        val id = parts[1].trim()
        val face = parts[2].trim().lowercase()
        if (!Handover.isDeviceId(id) && !SERVER_ID.matches(id)) return null
        if (face !in FACE_TOKENS) return null
        return Mark(id, face)
    }

    private val SERVER_ID = Regex("^MEST-PH-[0-9]{4}-[0-9]{5}$")

    /** A flat photograph is its own single "face". FaceWriter writes this
     *  token; LocalFaces.photoOf reads it. */
    const val PHOTO = "photo"

    /** The face list itself, not a shape. A length rule looked tidier and
     *  quietly threw away "up", which is two characters — the one face a
     *  regex of three-to-ten would have dropped without a sound. */
    private val FACE_TOKENS: Set<String> =
        Panorama.FACES.map { it.first }.toSet() + PHOTO

    /**
     * The QR as a square matrix of true = dark.
     *
     * Error correction M rather than L: the strip is small, the image may be
     * recompressed twice on its way through ImageMeter, and the extra
     * redundancy costs a few modules against a failure that costs the whole
     * mechanism. Margin 1 because the caption bar around it is already a
     * quiet zone.
     */
    fun matrix(payload: String, size: Int): Array<BooleanArray> {
        val hints = mapOf(
            EncodeHintType.ERROR_CORRECTION to ErrorCorrectionLevel.M,
            EncodeHintType.MARGIN to 1,
            EncodeHintType.CHARACTER_SET to "UTF-8",
        )
        val bits = QRCodeWriter().encode(
            payload, BarcodeFormat.QR_CODE, size, size, hints)
        return Array(bits.height) { y ->
            BooleanArray(bits.width) { x -> bits.get(x, y) }
        }
    }
}
